/*
 * To change this license headerchoose License Headers in Project Properties.
 * To change this template filechoose Tools | Templates
 * and open the template in the editor.
 */
package mcdonalds;

import javax.swing.ImageIcon;

/**
 *
 * @author felipe
 */
public class Image extends javax.swing.JFrame {

    /**
     * Creates new form Image
     */
    public Image(String image) {
        initComponents();
        
        lb_icon.setIcon(new ImageIcon(getClass().getResource("/mcdonalds/img/hamburguers/"+image+".png")));
        
        switch(image)
        {
            case "00000":
                lb_hamburguer.setText("triplo quarterao");
                break;
            case "00001":
                lb_hamburguer.setText("egg quarterao");
            break;
            case "00010":
                lb_hamburguer.setText("triplo tasty");
            break;
            case "00011":
                lb_hamburguer.setText("big tasty");
            break;
            case "00100":
                lb_hamburguer.setText("mcnifico bacon");
            break;
            case "00101":
                lb_hamburguer.setText("duplo quarterao");
            break;
            case "00110":
                lb_hamburguer.setText("big mac");
            break;
            case "00111":
                lb_hamburguer.setText("quarterao com queijo");
            break;
            case "01000":
                lb_hamburguer.setText("cheddar mcmelt");
            break;
            case "01001":
                lb_hamburguer.setText("triplo burger bacon");
            break;
            case "01010":
                lb_hamburguer.setText("triplo cheeseburger");
            break;
            case "01011":
                lb_hamburguer.setText("mcduplo");
            break;
            case "01100":
                lb_hamburguer.setText("duplo salada");
            break;
            case "01101":
                lb_hamburguer.setText("cheeseburger");
            break;
            case "01110":
                lb_hamburguer.setText("hamburger");
            break;
            case "01111":
                lb_hamburguer.setText("clubhouse");
            break;
            case "10000":
                lb_hamburguer.setText("quatrro formaggi");
            break;
            case "10001":
                lb_hamburguer.setText("crispy onion barbecue");
            break;
            case "10010":
                lb_hamburguer.setText("big tasty chicken bacon");
            break;
            case "10011":
                lb_hamburguer.setText("chicken supreme");
            break;
            case "10100":
                lb_hamburguer.setText("mcchicken");
            break;
            case "10101":
                lb_hamburguer.setText("mcfish");
            break;
            case "10110":
                lb_hamburguer.setText("extra chicken");
            break;
            case "10111":
                lb_hamburguer.setText("grand cheddar mcmelt bacon");
            break;
                
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lb_icon = new javax.swing.JLabel();
        lb_hamburguer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hamburguer");
        setMinimumSize(new java.awt.Dimension(550, 450));
        getContentPane().setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(lb_icon, gridBagConstraints);

        lb_hamburguer.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(lb_hamburguer, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lb_hamburguer;
    private javax.swing.JLabel lb_icon;
    // End of variables declaration//GEN-END:variables
}
